[supervisord]
nodaemon=true
pidfile=/tmp/supervisord.pid
logfile=/tmp/supervisord.log

[program:ruqqusservice]
directory=/opt/ruqqus/service
command=/opt/ruqqus/service/venv/bin/gunicorn ruqqus.__main__:app -w 3 -k gevent --max-requests 500 --max-requests-jitter 50 --bind 0.0.0.0:80
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:ruqqusrecomputes]
directory=/opt/ruqqus/service
command=/opt/ruqqus/service/venv/bin/python scripts/recomputes.py
autostart=false
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:ruqqusscheduler]
directory=/opt/ruqqus/service
command=/opt/ruqqus/service/venv/bin/python scripts/publish_scheduled.py
environment=PYTHONPATH="/opt/ruqqus/service"
autostart=true
autorestart=true
startsecs=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:ruqqustrending]
directory=/opt/ruqqus/service
command=/opt/ruqqus/service/venv/bin/python scripts/compute_trending.py
environment=PYTHONPATH="/opt/ruqqus/service"
autostart=true
autorestart=true
startsecs=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:ruqquscircles]
directory=/opt/ruqqus/service
command=/opt/ruqqus/service/venv/bin/python scripts/renew_circles.py
environment=PYTHONPATH="/opt/ruqqus/service"
autostart=true
autorestart=true
startsecs=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
